spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SAClass?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: SA
    password: SA
  mvc:
    view:
      suffix: .html
      prefix: /